name: tilix-test
adopt-info: tilix
version: git
version-script: git describe --tags
icon: data/icons/hicolor/512x512/apps/com.gexperts.Tilix.png
# license: MPL-2.0
description: |
  Tilix is a tiling terminal emulator.
  It lets you:
    • Layout terminals in any fashion by splitting them horizontally or
      vertically
    • Terminals can be re-arranged using drag and drop both within and between
      windows
    • Terminals can be detached into a new window via drag and drop
    • Input can be synchronized between terminals so commands typed in one
      terminal are replicated to the others
    • The grouping of terminals can be saved and loaded from disk
    • Terminals support custom titles
    • Color schemes are stored in files and custom color schemes can be created
      by simply creating a new file
    • Transparent background
    • Supports notifications when processes are completed out of view

  The application was written using GTK 3 and an effort was made to conform to
  GNOME Human Interface Guidelines (HIG). As a result, it does use client
  side-decorations, though it can be disabled if necessary.

  Tilix has been tested with GNOME and with Unity.

grade: stable
confinement: classic

parts:
  ldc:
    plugin: nil
    build-packages:
      - curl
    override-build:
      curl -fsS https://dlang.org/install.sh | bash -s ldc -p $SNAPCRAFT_PART_INSTALL
    prime: [-./*]

  vte:
    plugin: autotools
    source: https://gitlab.gnome.org/GNOME/vte.git
    source-depth: 1
    source-tag: vte-0-52
    build-attributes: ['no-system-libraries']
    build-packages:
      - gettext
      - gtk-doc-tools
      - intltool
      - libglib2.0-dev
      - libgnutls28-dev
      - libgtk-3-dev
      - libpango1.0-dev
      - libpcre2-dev
      - libxml2-utils
      - patchelf
    stage-packages:
      - libpcre2-8-0
    configflags:
      - --prefix=/usr
      - --disable-gtk-doc
      - --disable-static
      - --disable-vala
      - --enable-introspection=no
      - --with-gnutls
    prime:
      - usr/lib/*.so.*
      - usr/lib/*/*.so.*
      - usr/share/locale/**
    override-prime: |
      snapcraftctl prime
      env SNAPCRAFT_RPATH_RUNTIMES="gnome-3-26-1604" \
        $SNAPCRAFT_PRIME/../snap/set-snap-rpaths.sh \
          $SNAPCRAFT_PRIME/usr/lib/*.so.* \
          $SNAPCRAFT_PRIME/usr/lib/*/*.so.*

  tilix:
    plugin: nil
    source: .
    parse-info: [usr/share/metainfo/com.gexperts.Tilix.appdata.xml]
    build-packages:
      - desktop-file-utils
      - dub
      - gettext
      - libgtk-3-dev
      - libgtk2.0-bin
      - patch
      - patchelf
      - xdg-utils
    build-attributes: ['no-system-libraries']
    override-pull: |
      snapcraftctl pull
      patch -p1 < $SNAPCRAFT_STAGE/../snap/snap-enable.patch
    override-build: |
      set -x
      . $SNAPCRAFT_STAGE/ldc-*/activate
      HOME=$PWD dub build --build=release --compiler=ldc2 --verbose
      ./install.sh $SNAPCRAFT_PART_INSTALL/usr
    override-prime: |
      snapcraftctl prime
      env SNAPCRAFT_RPATH_RUNTIMES="gnome-3-26-1604" \
        $SNAPCRAFT_PRIME/../snap/set-snap-rpaths.sh $SNAPCRAFT_PRIME/usr/bin/*
    after:
      - vte
      - ldc

  launch-wrapper:
    plugin: nil
    source: snap
    override-build: |
      set +x
      RUNTIME=/snap/gnome-3-26-1604/current
      THEMES=/snap/gtk-common-themes/current
      ln -snfv $RUNTIME $SNAPCRAFT_PART_INSTALL/runtime
      ln -snfv $THEMES $SNAPCRAFT_PART_INSTALL/themes
      sed "s,@ARCH@,$SNAPCRAFT_ARCH_TRIPLET,g
           s,@RUNTIME@,\$SNAP/runtime,g
           s,@DATADIRS@,\$SNAP/themes/share,g" \
          tilix-launcher.in > tilix-launcher
      install -D -m755 tilix-launcher $SNAPCRAFT_PART_INSTALL/bin/tilix.wrapper

plugs:
  gnome-3-26-1604:
    interface: content
    target: $SNAP/runtime
    default-provider: gnome-3-26-1604

  common-themes:
    interface: content
    target: $SNAP/themes
    default-provider: gtk-common-themes

apps:
  tilix-test:
    environment:
      PATH: $SNAP/bin:$PATH
    command: tilix.wrapper
    common-id: com.gexperts.Tilix
    desktop: usr/share/applications/com.gexperts.Tilix.desktop
