#!/bin/bash

# On Fedora $SNAP is under /var and there is some magic to map it to /snap.
# We need to handle that case and reset $SNAP
SNAP=`echo $SNAP | sed -e "s|/var/lib/snapd||g"`

if [ "$SNAP_ARCH" == "amd64" ]; then
  ARCH="x86_64-linux-gnu"
elif [ "$SNAP_ARCH" == "armhf" ]; then
  ARCH="arm-linux-gnueabihf"
elif [ "$SNAP_ARCH" == "arm64" ]; then
  ARCH="aarch64-linux-gnu"
else
  ARCH="$SNAP_ARCH-linux-gnu"
fi

RUNTIME=$SNAP/runtime

export XDG_RUNTIME_DIR="/run/user/$(id -u)"
export XDG_CONFIG_DIRS="$SNAP/etc/xdg:$RUNTIME/etc/xdg:$XDG_CONFIG_DIRS"
export XDG_DATA_DIRS="$SNAP/usr/share:$RUNTIME/usr/share:$XDG_DATA_DIRS"

export GIO_MODULE_DIR=$RUNTIME/usr/lib/$ARCH/gio/modules
export GTK_PATH=$RUNTIME/usr/lib/$ARCH/gtk-3.0

exec $SNAP/usr/bin/tilix $@
